# Generated by Django 5.0.1 on 2024-02-06 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='pdf_files/')),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.ImageField(upload_to='pdf_pages/')),
                ('page_number', models.IntegerField()),
                ('uploaded_pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='Pdf_Extract.uploadedpdf')),
            ],
        ),
    ]
